name: Reusable SonarCloud Analysis

on:
  workflow_call:
    inputs:
      projectKey:
        required: true
        type: string
      organization:
        required: true
        type: string
      microserviceDir:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  sonar-analysis:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del microservicio
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Descargar el common-sonar.properties desde zenwk-workflows
      - name: Download common Sonar properties
        run: |
          curl -sL https://raw.githubusercontent.com/zenwk-org/zenwk-workflows/main/sonar/sonar-common.properties \
            -o ${{ inputs.microserviceDir }}/sonar-common.properties

      # 3. Configurar JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      # 4. Cache SonarCloud
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # 5. Cache Gradle dependencies y nativos
      - name: Cache Gradle dependencies and native binaries
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/native
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle
      
      # 6. Copy of file common/jacoco.gradle
      - name: Copy common Gradle scripts
        run: |
          cp zenwk-workflows/common-gradle/jacoco.gradle ${{ inputs.microserviceDir }}/gradle/jacoco.gradle
  
      # 7. Cache Gradle wrapper
      - name: Cache Gradle wrapper
        uses: actions/cache@v4
        with:
          path: ~/.gradle/wrapper/dists
          key: gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: gradle-wrapper-
      # 8. Compila y  ejecuta reporte de jacoco
      - name: Run tests and generate coverage
        working-directory: ${{ inputs.microserviceDir }}
        run: ./gradlew clean test jacocoTestReport

      # 9. Build y an√°lisis SonarCloud usando el archivo central
      - name: Build and analyze with SonarCloud
        working-directory: ${{ inputs.microserviceDir }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
        run: ./gradlew sonar -Dsonar.projectKey=${{ inputs.projectKey }} -Dsonar.organization=${{ inputs.organization }} -Dsonar.properties.file=sonar-common.properties --info