name: Reusable SonarCloud Analysis

on:
  workflow_call:
    inputs:
      projectKey:
        required: true
        type: string
      organization:
        required: true
        type: string
      projectDir:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  sonar-analysis:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Cache Node modules
      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: |
            ${{ inputs.projectDir }}/node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4. Install dependencies
      - name: Install dependencies
        working-directory: ${{ inputs.projectDir }}
        run: npm ci

      # 5. Run tests and generate coverage (Jest example)
      # - name: Run tests and coverage
      #   working-directory: ${{ inputs.projectDir }}
      #   run: npm run test -- --coverage

      - name: Run tests and coverage (handle no tests)
        working-directory: ${{ inputs.projectDir }}
        run: npm test -- --coverage || echo "No tests found, skipping..."

      # 6. Run SonarCloud scanner
      - name: SonarCloud Scan
        working-directory: ${{ inputs.projectDir }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          npx sonar-scanner \
          -Dsonar.projectKey=${{ inputs.projectKey }} \
          -Dsonar.organization=${{ inputs.organization }} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.sources=src \
          -Dsonar.tests=src/__tests__ \
          -Dsonar.test.inclusions="**/*.test.js,**/*.test.ts,**/*.test.tsx" \
          -Dsonar.exclusions="**/assets/**,**/styles/**,**/icons/**,**/constants/**,**/*.d.ts,**/interfaces/**,**/types/**,**/*.stories.tsx,**/*.config.ts,**/*.config.js" \
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
          -Dsonar.sourceEncoding=UTF-8 \
          -Dsonar.issue.ignore.multicriteria=e1,e2,e3,e4,e5 \
          -Dsonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S6754 \
          -Dsonar.issue.ignore.multicriteria.e1.resourceKey=**/*.tsx \
          -Dsonar.issue.ignore.multicriteria.e2.ruleKey=typescript:S1301 \
          -Dsonar.issue.ignore.multicriteria.e2.resourceKey=**/*.ts \
          -Dsonar.issue.ignore.multicriteria.e3.ruleKey=typescript:S6481 \
          -Dsonar.issue.ignore.multicriteria.e3.resourceKey=**/*.tsx \
          -Dsonar.issue.ignore.multicriteria.e4.ruleKey=typescript:S6571 \
          -Dsonar.issue.ignore.multicriteria.e4.resourceKey=**/*.tsx \
          -Dsonar.issue.ignore.multicriteria.e5.ruleKey=typescript:S7735 \
          -Dsonar.issue.ignore.multicriteria.e5.resourceKey=**/*.tsx
